### ISSUE TITLE
Change Some Values For Apex Video Config

### ISSUE THREAD

**Issue by Natram1zh** [couleur-tweak-tips/utils#8]
"setting.cl_particle_fallback_base"		"1"                      
 // Change this to higher value like 4 or 5... (higher value = less quality in particle) (Base for falling back to cheaper effects under load)

"setting.r_lod_switch_scale"		"0.1"                    
// don't go below 0.2 (just unplayable). below 0.3 you can't see enemies properly behind a object (Distance at where the low end models are loaded)

"setting.csm_cascade_res"		"512"                   
// Change this to 0 (lowest value) (reduce shadow quality but can't completely disable it)

**Comment by couleurm** [comment]
@zazkm
